// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn7eBSWnO7HSY9ukgaYQ3cuOngQNABdGc',
    appId: '1:596362878013:web:22530f1dfc9a45c129de54',
    messagingSenderId: '596362878013',
    projectId: 'food-recipe-a4bca',
    authDomain: 'food-recipe-a4bca.firebaseapp.com',
    storageBucket: 'food-recipe-a4bca.firebasestorage.app',
    measurementId: 'G-2WKQ2N2V18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApdE-mHMO_RpdB7-ObaE01CQVy3L_0NGY',
    appId: '1:596362878013:android:7a76453222ec798929de54',
    messagingSenderId: '596362878013',
    projectId: 'food-recipe-a4bca',
    storageBucket: 'food-recipe-a4bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1NaP-wOD1nyVg8vD9ceurTwgX7hyW-s',
    appId: '1:596362878013:ios:18ba2d0db014e26d29de54',
    messagingSenderId: '596362878013',
    projectId: 'food-recipe-a4bca',
    storageBucket: 'food-recipe-a4bca.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI1NaP-wOD1nyVg8vD9ceurTwgX7hyW-s',
    appId: '1:596362878013:ios:18ba2d0db014e26d29de54',
    messagingSenderId: '596362878013',
    projectId: 'food-recipe-a4bca',
    storageBucket: 'food-recipe-a4bca.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn7eBSWnO7HSY9ukgaYQ3cuOngQNABdGc',
    appId: '1:596362878013:web:24279bb932a0998a29de54',
    messagingSenderId: '596362878013',
    projectId: 'food-recipe-a4bca',
    authDomain: 'food-recipe-a4bca.firebaseapp.com',
    storageBucket: 'food-recipe-a4bca.firebasestorage.app',
    measurementId: 'G-KMJ126QW8Q',
  );
}
